version: 1.0.{build}

environment:
  my_variable:
    secure: XhpTK+stym7O1dkZ24bIuHxOJtBbypMurYNX/I7m3OliWVE+4CCeiVr573SD6S+m

configuration:
- Debug
- Release
platform:
- Any CPU
- x86
- x64
nuget:
  project_feed: true
build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  publish_aspnet_core: true
  publish_core_console: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: 4BJNmm+fEUPamag0fmQhNePDlkGpJ8F9UcySdsZ/prE=
notifications:
- provider: Email
  to:
  - tinylit@foxmail.com
  subject: skybuilding
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false