version: 1.0.{build}
branches:
  only:
  - master
environment:
  my_variable:
    secure: wNX2iDZ6vz+R7otYxAXPZcJlSURjT1/f9I2/77C0HOOOyKtJ97S09g4Qxun/iQ1m
  DEV-DATABASE-SQLSEVER-DOMAIN:
    secure: RWjD1YlUrzmeqLaRS1d31w==
  DEV-DATABASE-MYSQL-DOMAIN:
    secure: Vgyz+NE+M+ZQc7AYGJBSfw==
  DEV-DATABASE-SQLSEVER-USER:
    secure: e0KSlgsDXc0qVKE7Rv5j+A==
  DEV-DATABASE-SQLSEVER-PASSWORD:
    secure: nAJtxhAiO3Ra25gV5uGoQ4thvJwf2AHkVymFQes/CMk=
  DEV-DATABASE-MYSQL-USER:
    secure: e0KSlgsDXc0qVKE7Rv5j+A==
  DEV-DATABASE-MYSQL-PASSWORD:
    secure: nAJtxhAiO3Ra25gV5uGoQ4thvJwf2AHkVymFQes/CMk=
image: Visual Studio 2019
configuration:
- Debug
- Release
platform:
- x86
- x64
- Any CPU
clone_depth: 5
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
notifications:
- provider: Email
  to:
  - tinylit@foxmail.com
  subject: skybuilding
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false