version: 1.0.{build}
skip_tags: true
skip_commits:
  files:
    - '**/*.md'
    - '**/*.txt'
    - '**/*.png'
    - '**/*.jpg'
image: Visual Studio 2019
configuration:
- Debug
- Release
platform: Any CPU
clone_depth: 5
environment:
  DEV-DATABASE-SQLSEVER-DOMAIN:
    secure: gDFNTcGbJURYooTneY4HWA==
  DEV-DATABASE-SQLSEVER-USER: orm
  DEV-DATABASE-SQLSEVER-PASSWORD: Password12!
  DEV-DATABASE-SQLSERVER-DATABASE: yep_sky_orm
services:
- mssql2008r2sp2
- mysql
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
before_package:
- ps: .\build.ps1
artifacts:
- path: .\.nupkgs\*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: tiqrW+/1hsyCLjZu/VFQOX6ERU/AQ8X9r5mNRFUPAocmkGx2+fLJ/hEltdrHUIDx
  artifact: .\.nupkgs\*.nupkg
  on:
    branch: master
notifications:
- provider: Email
  to:
  - tinylit@foxmail.com
  subject: skybuilding
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false