version: 1.0.{build}
configuration:
- Debug
- Release
platform:
- Any CPU
- x86
- x64
nuget:
  project_feed: true
build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  publish_aspnet_core: true
  publish_core_console: true
  verbosity: minimal
notifications:
- provider: Email
  to:
  - tinylit@foxmail.com
  subject: skybuilding
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false