version: 1.0.{build}
branches:
  only:
  - master
environment:
  my_variable:
    secure: wNX2iDZ6vz+R7otYxAXPZcJlSURjT1/f9I2/77C0HOOOyKtJ97S09g4Qxun/iQ1m
image: Visual Studio 2017
configuration:
- Debug
- Release
platform:
- Any CPU
clone_depth: 5
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
notifications:
- provider: Email
  to:
  - tinylit@foxmail.com
  subject: skybuilding
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false