version: 1.0.{build}
branches:
  only:
  - master
configuration:
- Debug
- Release
platform:
- Any CPU
clone_depth: 5
environment:
  NUGET-SECRET:
    secure: wNX2iDZ6vz+R7otYxAXPZcJlSURjT1/f9I2/77C0HOOOyKtJ97S09g4Qxun/iQ1m
  DEV-DATABASE-SQLSEVER-DOMAIN:
    secure: RWjD1YlUrzmeqLaRS1d31w==
  DEV-DATABASE-MYSQL-DOMAIN:
    secure: Vgyz+NE+M+ZQc7AYGJBSfw==
  DEV-DATABASE-SQLSEVER-USER:
    secure: e0KSlgsDXc0qVKE7Rv5j+A==
  DEV-DATABASE-SQLSEVER-PASSWORD:
    secure: nAJtxhAiO3Ra25gV5uGoQ4thvJwf2AHkVymFQes/CMk=
  DEV-DATABASE-MYSQL-USER:
    secure: e0KSlgsDXc0qVKE7Rv5j+A==
  DEV-DATABASE-MYSQL-PASSWORD:
    secure: nAJtxhAiO3Ra25gV5uGoQ4thvJwf2AHkVymFQes/CMk=
image: Visual Studio 2019
services:
  - mssql2016
  - mysql
init:
    <#
        .SYNOPSIS
            Set all installed instances of SQL server to dynamic ports
    #>
    Get-ChildItem -Path 'HKLM:\SOFTWARE\Microsoft\Microsoft SQL Server\' |
    Where-Object {
        $_.Name -imatch 'MSSQL[_\d]+\.SQL.*'
    } |
    ForEach-Object {

        Write-Host "Setting $((Get-ItemProperty $_.PSPath).'(default)') to dynamic ports"
        Set-ItemProperty (Join-Path $_.PSPath 'mssqlserver\supersocketnetlib\tcp\ipall') -Name TcpDynamicPorts -Value '0'
        Set-ItemProperty (Join-Path $_.PSPath 'mssqlserver\supersocketnetlib\tcp\ipall') -Name TcpPort -Value ([string]::Empty)
    }
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
notifications:
- provider: Email
  to:
  - tinylit@foxmail.com
  subject: skybuilding
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false