version: 1.0.{build}
branches:
  only:
  - master
configuration:
- Debug
- Release
platform: Any CPU
clone_depth: 5
environment:
  DEV-DATABASE-SQLSEVER-DOMAIN:
    secure: gDFNTcGbJURYooTneY4HWA==
  DEV-DATABASE-SQLSEVER-USER:
    secure: e0KSlgsDXc0qVKE7Rv5j+A==
  DEV-DATABASE-SQLSEVER-PASSWORD:
    secure: nAJtxhAiO3Ra25gV5uGoQ4thvJwf2AHkVymFQes/CMk=
  DEV-DATABASE-SQLSERVER-DATABASE:
    secure: ODbpu9o1oZ6BmR2jaDYPFg==
image: Visual Studio 2019
skip_tags: true
skip_commits:
  files:
    - '**/*.md'
    - '**/*.txt'
    - '**/*.png'
    - '**/*.jpg'
services:
  - mssql2008r2sp2
  - mysql
# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
notifications:
- provider: Email
  to:
  - tinylit@foxmail.com
  subject: skybuilding
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false