version: 1.0.{build}
configuration:
- Debug
- Release
platform:
- Any CPU
- x86
- x64
nuget:
  project_feed: true
build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  publish_aspnet_core: true
  publish_core_console: true
  verbosity: minimal
deploy:
- provider: NuGet
  server: https://www.myget.org/F/stackoverflow/api/v2
  api_key:
    secure: 08NAqKgLhpq2dIiMyO5VxRITpfXTGQMc0N2U3UVe5IZX2wU6j2aFy/+DlAGHi8t/CBGiKSPx1XFzabLOmeoLFo1QHFnWeClkIm8q4LN372U=
  symbol_server: https://www.myget.org/F/stackoverflow/symbols/api/v2/package
  on:
    branch: master
- provider: NuGet
  api_key:
    secure: 26UCLCtjeu/oKElgDJn7hIWfzMu0x+U7iIkoVAdQ1xc5XDBjmZzCVa6Eomamq0NK
notifications:
- provider: Email
  to:
  - tinylit@foxmail.com
  subject: skybuilding
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false